version: "3"

volumes:
  mysql_data:
  redis_data:


services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: restaurant
      MYSQL_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - "3336:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./internal/data/seed:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine3.21
    container_name: redis
    restart: always
    ports:
      - "6399:6379"
    volumes:
      - redis_data:/data
