application:
  name: "LearnRecord"
  port: 8080

database:
  host: localhost
  port: 3336
  db_name: gateway
  username: root
  password: 123456

redis:
  host: localhost
  port: 6399
  password: 
  database: 0

jwt:
  secret: secret
  expiration: 604800